/** Shared inline styles — uses host CSS custom properties + color-mix for theme consistency */
export const s = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
    padding: "16px",
    color: "var(--foreground, #e0e0e0)",
  },
  section: {
    background: "var(--card, #1a1a1a)",
    border: "1px solid var(--border, #333)",
    borderRadius: "12px",
    padding: "16px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "12px",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: { fontSize: "14px", fontWeight: 600, color: "var(--foreground, #e0e0e0)" },
  card: {
    background: "var(--background, #111)",
    border: "1px solid var(--border, #333)",
    borderRadius: "10px",
    padding: "12px 16px",
    cursor: "pointer" as const,
    transition: "border-color 0.15s, background 0.15s",
  },
  cardSelected: {
    background: "color-mix(in srgb, var(--primary, #3b82f6) 10%, var(--background, #111))",
    border: "1px solid color-mix(in srgb, var(--primary, #3b82f6) 60%, var(--border, #333))",
    borderRadius: "10px",
    padding: "12px 16px",
    cursor: "pointer" as const,
  },
  cardName: { fontSize: "14px", fontWeight: 600, color: "var(--foreground, #e0e0e0)" },
  cardMeta: { fontSize: "12px", color: "var(--muted-foreground, #888)", marginTop: "4px" },
  btn: {
    appearance: "none" as const,
    background: "color-mix(in srgb, var(--primary, #3b82f6) 18%, transparent)",
    color: "var(--primary, #93c5fd)",
    border: "1px solid color-mix(in srgb, var(--primary, #3b82f6) 40%, var(--border, #333))",
    borderRadius: "999px",
    padding: "6px 14px",
    fontSize: "12px",
    fontWeight: 500,
    cursor: "pointer" as const,
  },
  btnDanger: {
    appearance: "none" as const,
    background: "color-mix(in srgb, #ef4444 15%, transparent)",
    color: "#f87171",
    border: "1px solid color-mix(in srgb, #ef4444 40%, var(--border, #333))",
    borderRadius: "999px",
    padding: "6px 14px",
    fontSize: "12px",
    fontWeight: 500,
    cursor: "pointer" as const,
  },
  btnDisabled: {
    appearance: "none" as const,
    background: "var(--muted, #1a1a1a)",
    color: "var(--muted-foreground, #555)",
    border: "1px solid var(--border, #333)",
    borderRadius: "999px",
    padding: "6px 14px",
    fontSize: "12px",
    cursor: "not-allowed" as const,
  },
  btnSuccess: {
    appearance: "none" as const,
    background: "color-mix(in srgb, #22c55e 15%, transparent)",
    color: "#4ade80",
    border: "1px solid color-mix(in srgb, #22c55e 40%, var(--border, #333))",
    borderRadius: "999px",
    padding: "4px 10px",
    fontSize: "11px",
    fontWeight: 500,
    cursor: "pointer" as const,
  },
  pill: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "999px",
    border: "1px solid var(--border, #333)",
    padding: "2px 10px",
    fontSize: "11px",
    color: "var(--muted-foreground, #888)",
    background: "transparent",
    cursor: "pointer" as const,
  },
  pillActive: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "999px",
    border: "1px solid color-mix(in srgb, var(--primary, #3b82f6) 60%, var(--border, #333))",
    padding: "2px 10px",
    fontSize: "11px",
    color: "var(--primary, #93c5fd)",
    background: "color-mix(in srgb, var(--primary, #3b82f6) 15%, transparent)",
    cursor: "pointer" as const,
  },
  badge: (color: string) => ({
    display: "inline-flex",
    alignItems: "center",
    background: `color-mix(in srgb, ${color} 15%, transparent)`,
    color,
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "11px",
    fontWeight: 500,
  }),
  tag: {
    display: "inline-flex",
    alignItems: "center",
    background: "color-mix(in srgb, var(--foreground, #fff) 8%, transparent)",
    borderRadius: "999px",
    padding: "2px 10px",
    fontSize: "11px",
    color: "var(--muted-foreground, #888)",
  },
  input: {
    width: "100%",
    background: "var(--background, #111)",
    border: "1px solid var(--border, #333)",
    borderRadius: "8px",
    padding: "6px 10px",
    color: "var(--foreground, #e0e0e0)",
    fontSize: "13px",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  empty: { color: "var(--muted-foreground, #555)", fontSize: "13px", textAlign: "center" as const, padding: "24px" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "12px",
  },
  row: { display: "flex", gap: "8px", alignItems: "center" },
  loading: {
    display: "flex",
    justifyContent: "center",
    padding: "32px",
    color: "var(--muted-foreground, #888)",
    fontSize: "13px",
  },
};
